"""create committees and committee memberships

Revision ID: 1743274d7a58
Revises: e94b4d92c96b
Create Date: 2026-10-09 05:01:31.703881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1743274d7a58'
down_revision: Union[str, Sequence[str], None] = 'e94b4d92c96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('committee_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('committee_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('committee_role', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("committee_role IN ('head', 'executive', 'coordinator', 'member')", name='valid_committee_role'),
    sa.CheckConstraint("verification_status != 'approved' OR (verified_by IS NOT NULL AND verified_at IS NOT NULL)", name='approved_requires_verifier'),
    sa.CheckConstraint("verification_status IN ('pending', 'approved', 'rejected')", name='valid_verification_status'),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committee_id', 'user_id', name='uq_committee_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('committee_members')
    op.drop_table('committees')
    # ### end Alembic commands ###
