"""create venues and events

Revision ID: 64f6563d3960
Revises: 1743274d7a58
Create Date: 2026-10-09 05:13:23.972908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f6563d3960'
down_revision: Union[str, Sequence[str], None] = '1743274d7a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_venues_positive_capacity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('committee_id', sa.Uuid(), nullable=False),
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'cancelled')", name='ck_events_valid_status'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_events_valid_times'),
    sa.CheckConstraint('max_participants IS NULL OR max_participants > 0', name='ck_events_positive_capacity'),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_committee_starts_at', 'events', ['committee_id', 'starts_at'], unique=False)
        # Enable GiST support for UUID equality
    op.execute(
        "CREATE EXTENSION IF NOT EXISTS btree_gist"
    )

    # Prevent overlapping confirmed events in the same venue
    op.execute("""
        ALTER TABLE events
        ADD CONSTRAINT no_confirmed_venue_overlap
        EXCLUDE USING gist (
            venue_id WITH =,
            tstzrange(starts_at, ends_at, '[)') WITH &&
        )
        WHERE (status = 'confirmed')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_committee_starts_at', table_name='events')
    op.drop_table('events')
    op.drop_table('venues')
    # ### end Alembic commands ###
